name: Build Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare database
        run: |
          cargo install sqlx-cli
          sqlx database create
          sqlx migrate run
          cargo sqlx prepare
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
